### ISSUE TITLE
how hard is it to get rid of build dependencies of oasis

### ISSUE THREAD

**Issue by bobzhang** [janestreet/ppx_variants_conv#2]
since most ppx from janestreet is  small to medium size, is it possible to get rid of oasis dependency(or minimum dependency the best), we had some problem to build it on windows

**Comment by ghost** [comment]
The release tarballs don't have this dependency, you can download them here: https://ocaml.janestreet.com/ocaml-core/113.24/files/

**Comment by yminsky** [comment]
Closing.
