### ISSUE TITLE
Variants named "Open" behave badly

### ISSUE THREAD

**Issue by yminsky** [janestreet/ppx_variants_conv#5]
```
utop # type t = Open [@@deriving variants];;
type t = Open                                                                                                                                                                                                      val open : t = Open                                                                                                                                                                                                module Variants :
  sig
    val open : t Variant.t
    val fold : init:'a -> open:('a -> t Variant.t -> 'b) -> 'b
    val iter : open:(t Variant.t -> unit) -> unit
    val map : t -> open:(t Variant.t -> 'a) -> 'a
    val to_rank : t -> int
    val to_name : t -> bytes
    val descriptions : (bytes * int) list
  end
```

I'm surprised this even works, but in any case the values called "open" can't actually be referred to, since open is a keyword.

**Comment by ghost** [comment]
We should check in `Ast_invariants` all identifiers generated by ppx rewriters and pre-processors. Though i'm not sure of the cost. Then code generators would be forced to handle problematic case like this

**Comment by bmillwood** [comment]
On a similar vein, but less critically, `type t = Fold` leads to the `t Variant.t` being shadowed.

**Comment by v-gb** [comment]
Collisions with keywords were fixed in 2018 by appending underscores where necessary. It doesn't solve the problem of collisions between field names and function names, but I'm going to call this good enough.
