### ISSUE TITLE
Please (re-)support polymorphic variant inclusion

### ISSUE THREAD

**Issue by drvink** [janestreet/ppx_variants_conv#6]
A previous version of `ppx_variants_conv` supported this, but it apparently wasn't quite right, and instead of being fixed, was [removed entirely](https://github.com/janestreet/ppx_variants_conv/blob/1660b1e427793f77c35e23f730298a4b420523b9/CHANGES.md#1134300). I don't see any reason, however, why cases like this should not be supported:

```ocaml
type a = [
  | `a
  | `b
]

type a1 = [
  | `a1
  | `b1
]

type all_the_guys = [
  | a
  | a1
] [@@deriving variants]
```

This case ought to be possible to make work, given that there need not even be code to ensure that first-class constructors (i.e. functions) are not emitted multiple times, as might happen if we had instead written:

```ocaml
type a = [
  | `a
  | `b
] [@@deriving variants]

type a1 = [
  | `a1
  | `b1
]

type all_the_guys = [
  | a
  | a1
] [@@deriving variants]
```

But this should be possible to support too: simply don't emit the non-module functions (i.e. the ones that live outside `Variants_of_all_the_guys`) for any inherited constructors that are part of a type which itself derived `variants`--so in this case, when processing `all_the_guys`, the constructor functions for `a` would not be emitted (this would have already happened when processing `a`), but the ones for `a1` would be. (Am I misunderstanding anything here?)

I made a go at modifying `ppx_variants_conv` to support this, but as far as I can tell, the compiler front-end API doesn't provide any way for us to be able to get info about `a` and `a1`'s constructors at the time we're processing `all_the_guys`, and based on how `ppx_variants_conv` is invoked by `ppx_type_conv`, there's not even any obvious way to hack in something like a hash table of type declarations keyed by fully-qualified path to be used when processing `all_the_guys`, since I don't see any way of getting the enclosing scope of a type either (it seems `ppx_type_conv` would instead be needing to pass `module_declaration`s or `module_type_declaration`s to `ppx_variants_conv`).

**Comment by drvink** [comment]
Updated the original comment to reflect my attempts at trying to add this and fixed some dumb typos. Some feedback would be nice, since the removal of this feature is preventing upgrading a project to newer versions of its dependencies (other Jane Street libraries) and causing versioning hell.

**Comment by ghost** [comment]
/cc @sliquister

I had a look at the internal change that removed this feature. The Changelog got trimmed; support for polymorphic variants was unused inside Jane Street and it was dubious for the reason you mentioned, so it was removed.

I suppose you could support polymorphic variants fully by doing something like this:

```ocaml
module Variants_all_the_guys = struct
   includes Variants_a
   includes Variants_b

   let kiter k = Variants_a.kiter (Variants_a1.kiter k)
   let iter = kiter ()
   
  let to_rank = function
    | #a as x -> Variants_a.to_rank x
    | #a1 as x -> Variants_a1.to_rank x

  ...
end
```

**Comment by v-gb** [comment]
Can you say how you used the generated code? The inferred interface for the example you gave is:

```ocaml
type a = [ `a | `b ]
type a1 = [ `a1 | `b1 ]
type all_the_guys = [ `a | `a1 | `b | `b1 ]
module Variants_of_all_the_guys :
  sig
    val fold : init:'a -> a:('a -> 'b) -> a1:('b -> 'c) -> 'c
    val iter : a:(unit -> unit) -> a1:(unit -> unit) -> unit
    val map : [< `a | `a1 | `b | `b1 ] -> a:'a -> a1:'a -> 'a
    val descriptions : (bytes * int) list
  end
```

so it's hard to imagine why any part of this is useful.

**Comment by drvink** [comment]
```ocaml
module Foo = struct
  type a = [
    | `a1
    | `a2
  ] [@@deriving bin_io, compare, enumerate, sexp]

  type b = [
    | `b1
    | `b2
  ] [@@deriving bin_io, compare, enumerate, sexp]

  type t = [
    | a
    | b
  ] [@@deriving bin_io, compare, enumerate, sexp, variants]
end
```

**Comment by v-gb** [comment]
This is how you use the preprocessor. I meant: if you remove the [@@deriving variants] on that last type, what's the sort of code that doesn't type anymore? Which generated values do you call?

**Comment by drvink** [comment]
Oh, I misunderstood, sorry. Well, say you add one more case to `t`:

```ocaml
type t = [
  | a
  | b
  | `q
] [@@deriving bin_io, compare, enumerate, sexp, variants]
```

Without the support for inclusion, we won't have generated for us

```ocaml
val q : [> `q ]
```

or the functions in `Variants_of_t`, of course.

**Comment by v-gb** [comment]
We could generate the toplevel functions I suppose. The module still doesn't seem to make much sense to me.
It's a local change to split the type in two:

```ocaml
type t2 = [ `q ] [@@deriving variants]
type t = [ a | b | t2 ]
```

Does that not do what you want? At least it's clear what the generated code should do in this case.

**Comment by drvink** [comment]
That will work for the top-level functions (which might be good enough for now). But what if we have this?

```ocaml
type a = [ `a1 ] [@@deriving variants]
type b = [ `b1 ] [@@deriving variants]
type c = [ a | b | `c1 ] [@@deriving variants]
```

In addition to the usual results for `a` and `b`, I would expect the `[@@deriving variants]` on `c` to produce:

```ocaml
val c1 : [> `c1 ]

module Variants_of_c : sig
  val a1 : [> `a1 ] Variantslib.Variant.t
  val b1 : [> `b1 ] Variantslib.Variant.t
  val c1 : [> `c1 ] Variantslib.Variant.t
  val fold :
    init:'a ->
    a1:('a -> [> `a1 ] Variantslib.Variant.t -> 'b) ->
    b1:('b -> [> `b1 ] Variantslib.Variant.t -> 'c) ->
    c1:('c -> [> `c1 ] Variantslib.Variant.t -> 'd) -> 'd
  val iter :
    a1:([> `a1 ] Variantslib.Variant.t -> unit) ->
    b1:([> `b1 ] Variantslib.Variant.t -> unit) ->
    c1:([> `c1 ] Variantslib.Variant.t -> unit) -> unit
  val map :
    [< `a1 | `b1 | `c1 ] ->
    a1:([> `a1 ] Variantslib.Variant.t -> 'a) ->
    b1:([> `b1 ] Variantslib.Variant.t -> 'a) ->
    c1:([> `c1 ] Variantslib.Variant.t -> 'a) -> 'a
  val descriptions : (string * int) list
end
```

We would raise an error if `c` tried to include types that did not themselves have `[@@deriving variants]`.

Sorry for the scatterbrained posts--I think between your proposal and this one, the generator's behavior would be consistent/make sense.

**Comment by v-gb** [comment]
I'm just confused now: you claim the rejection of variant inclusion in newer versions stops you from upgrading, but you are asking for things that were never supported.

**Comment by drvink** [comment]
I was attempting to show examples that would solve my original problem initially, but realized while doing so that the overall functionality could be made better. I conflated these in the code I showed, which was unclear.

The top-level function generation that you proposed would be good enough for me, but ideally (i.e. *I* don't require it, but it would be more complete and more in line with how I would expect it to behave) if the module were to also do what I proposed.

**Comment by v-gb** [comment]
Making [@@deriving variants] behave on variant inclusion as if the variants were inlined is complicated, you'd need functions and types to take continuations, like @diml  was saying. It's not possible to access the definitions of the other types in a preprocessor.

**Comment by drvink** [comment]
I see. Are there any ppx modules that do this to use as an example?

**Comment by v-gb** [comment]
I don't know of any ppx that does something like that. Also, thinking about it, I think it would run into the value restriction, if you don't add an extra unit parameter, which would change the interface of the generated code.

**Comment by v-gb** [comment]
Trying to figure out what to do here. Do people still care about this?

The easier thing to do is nothing obviously. Just adding the ``let foo x = `foo x`` functions for the direct constructors (not the one that gets included) seems not great but ok. Anything else seems quite a bit harder, and given the small benefit I wouldn't implement it.

**Comment by drvink** [comment]
IIRC I originally brought this up since the removal was causing trouble for BAP, but it's long since been worked around, so unless @ivg has something to say, I don't mind if you simply close this. Thanks for looking into it again.
